## Database Configuration for Aiven MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql-20b7eb97-chirayu-2805.aivencloud.com}:${DB_PORT:27415}/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD}

## Specify the database driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Spring Boot Production Configuration
spring.jpa.hibernate.ddl-auto=update
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html
spring.web.resources.cache.enabled=false