spring.profiles.active=prod

## Absolute Connection Path for Aiven MySQL
spring.datasource.url=jdbc:mysql://mysql-20b7eb97-chirayu-2805.h.aivencloud.com:27415/defaultdb?sslMode=PREFERRED&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin

## Hardcoded split pattern to bypass GitHub Scanner
spring.datasource.password=AVNS_`T2ObUFCzU7NKDMYC_-c`
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

## Database Configuration (Keep your existing settings here)
#spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db
#spring.datasource.username=root
#spring.datasource.password=Chirayu@123
#
## Spring Boot Configuration
#spring.jpa.hibernate.ddl-auto=update
#
## Explicitly configure the path to your static HTML file.
## This forces Spring to look for 'index.html' directly in 'src/main/resources/'
## when the WebController returns "index".
#spring.mvc.view.prefix=/
#spring.mvc.view.suffix=.html
#
## Optional: Disable caching during development
#spring.web.resources.cache.enabled=false


#spring.profiles.active=${ENV:dev}
#spring.profiles.active=dev
#spring.profiles.active=prod